import { Alert, AlertTitle, Typography } from "@mui/material";

interface DisclaimerProps {
  compact?: boolean;
}

export default function Disclaimer({ compact }: DisclaimerProps) {
  if (compact) {
    return (
      <Alert severity="warning" variant="outlined" sx={{ borderRadius: 2 }}>
        This result is generated by an AI model for screening/research purposes only. It is not a medical diagnosis.
      </Alert>
    );
  }
  return (
    <Alert severity="warning" variant="outlined" sx={{ borderRadius: 2 }}>
      <AlertTitle sx={{ fontWeight: 600 }}>Important</AlertTitle>
      <Typography variant="body2">
        This result is generated by an artificial intelligence model and is intended for screening/research
        assistance only. It is not a medical diagnosis. Clinical decisions should be made by a qualified
        healthcare professional.
      </Typography>
    </Alert>
  );
}
